---
title: "Sitecomparator"
author: "Carl Fortelius"
format: html
editor: visual
toc: false  # Automatically generates a TOC
toc-depth: 3
editor_options: 
  chunk_output_type: console
execute:
  echo: false
---

## 

```{r, message=FALSE, "Libraries", results='hide'}
#| echo: false
library("harp")
library("tidyverse")
library("here")
library("argparse")
library(zoo)
library("htmltools")
```

Setting up the environment

```{r, message=FALSE, "Setting up the environment"}
#| echo: false
source(here("config/config_atos.R"))
source(here("R/fn_plot_data_at_mast.R"))
source(here("R/fn_select_parameter.R"))

parser <- ArgumentParser()

#parser$add_argument("-start_date", type="character",
#                    default=NULL,
#                    help="First date to process [default %(default)s]",
#                    metavar="Date in format YYYYMMDDHH")

#parser$add_argument("-end_date", type="character",
#                    default=NULL,
#                    help="Final date to process [default %(default)s]",
#                    metavar="Date in format YYYYMMDDHH")

args <- parser$parse_args()

CONFIG <- conf_get_config()
params <- CONFIG$params_details

obs_path <- CONFIG$data$obs_path
mod_path <- CONFIG$data$mod_path
rds_path <- CONFIG$data$rds_input_path
rdsfile  <- CONFIG$data$rds_input_name
metadata <- CONFIG$metadata
```

Function to read mast data

```{r, message=FALSE, "Function to read mast data"}
#| echo: false
read_mfile <- function(
    datadir       = NA,
    mast          = NA, # list of attributes for a site
    model         = NA, # list of attributes for a model
    lead_time     = NA,
    v_type        = NA,
    missing_value = -99999
) {
    #model <- metadata$Models$MEP0
  #mast <- metadata$Sites$SODA
  #datadir = "/ec/res4/scratch/fnm/MastVerifData/obs"
  ##parameters <- unlist(strsplit( model$parameters ,","))
  #file <- "/ec/res4/scratch/fnm/MastVerifData/fc/CABA/MEP0/Fcst_MEP0_CABA_20230924_00.txt"
  #v_type <- "Mast"

  if (v_type == "Mast" | v_type == "Flux") {
    prefix <- "Meas"
    parameters <- unlist(strsplit(mast[[{{v_type}}]]$parameters,","))
    n_max = Inf # Take all there is
    file_list <- list.files(path = paste(datadir,mast$name,sep="/"), 
                            pattern = paste(prefix,
                                            mast$name,
                                            v_type,
                                            "*",
                                            sep="_"),
                            full.names = TRUE)
  } else if (v_type == "Model"){
    prefix <- "Fcst"
    parameters <- unlist(strsplit( model$parameters ,","))
    n_max <- 24 #Some models provide more than 24 steps
    file_list <- list.files(path=paste(mod_path,
                                       mast$name,
                                       model$name,
                                       sep="/"),
                            pattern=glob2rx(
                              paste(prefix,model$name, 
                                    mast$name, "*",
                                    sep="_")),
                            full.names = TRUE)
  } else { stop("what what what")}

  # Read and process each text file
  lapply(file_list, function(file) {
    # Read the text file and convert to tibble,
    buffer <- read_table(
      file,
      col_names = FALSE,
      show_col_types = FALSE,
      n_max = n_max
    )  |>   
      select(1:length(parameters)) |>
      rename_with(~ parameters, 1:length(parameters))
    
    if (v_type == "Mast" | v_type == "Flux") {
      buffer <- buffer |> 
        mutate_all(~ifelse(.== -99999, NA, .))   |>
        mutate(
          valid_dttm =  ymd_hm(valid_dttm),
          SID=mast$SID, 
          lon=mast$lon,
          lat=mast$lat, 
          elev=mast$elev,
          valid_hour = format(valid_dttm, format = "%H:%M"))
      if (mast$name == "LIND") {
        buffer <- buffer |>
          mutate(SWDIF = NA,
                 DNI = NA)
      }
    } else if (v_type == "Model"){
      buffer <- buffer |> 
        mutate_all(~ifelse(.== -99999, NA, .)) |>
        mutate(
          valid_dttm = ymd_hm(valid_dttm * model$minutefactor),
          valid_dttm = case_when( #Some FRAR data are valid at h-1min
            minute(valid_dttm) == 59
            ~ valid_dttm+minutes(1),
            TRUE ~ valid_dttm),
          fcst_dttm = first(valid_dttm) - seconds(model$first_lead_time),
          lead_time = as.numeric(
            difftime(valid_dttm, fcst_dttm, units = "secs")),
          fcst_model=model$name, 
          SID=mast$SID, 
          model_elevation = mast$elev, 
          fcst_cycle="0")
    }
    return(buffer)}) |> bind_rows()
} 
#see: https://fminwp.fmi.fi/mastverif/docs/Mast_verif_dataDescr.pdf

```

Function to add derived parameters

```{r, message=FALSE, "Add derived parameters to data frame"}
#| echo: false
#| 
add_derived_parameters <- function(df){
  
# adding derived parameters
#  RNET:   Net radiation
#   STH:   Total surface turbulent heat flux (sensible and latent)
# RESID:   Implied heat flux into the soil
# SFCFORC: Forcing quasi external to the surface, i.e. Downwelling
#          radiation - reflected radiation
#   TSRAD: Surface radiative temperature  
#     UDT: Wind speed times air-surface temperature difference
#  
  df <- mutate(df, RNET=NA, STH=NA, RESID=NA, SFCFORC=NA, TSRAD=NA, UDT=NA)
  
     if( all(c("SSH", "SLH") %in% names(df)) ){
        print("Adding derived parameter: STH")
         df <- mutate(df,
           STH   = SSH + SLH
         )}
  
    if( all(c("GLOB","LWDN","SWUP","LWUP", "SSH", "SLH") %in% names(df)) ){
        print("Adding derived parameter: RESID")
        df <- mutate(df, 
           RESID   = GLOB + LWDN - SWUP - LWUP - SSH - SLH
        )}
  
  if( all(c("GLOB","LWDN","SWUP","LWUP") %in% names(df)) ){
    print("Adding derived parameters: RNET, SFCFORC, TSRAD")
    df <- mutate(df, 
           RNET    = GLOB + LWDN - SWUP - LWUP,
           SFCFORC = GLOB + LWDN - SWUP,
           TSRAD   = (LWUP/5.67e-8)^0.25 - 273.15
    )}
  
   if( all(c("LWUP", "TL") %in% names(df)) ){
         print("Adding derived parameter:  DTLTS")
         df <- mutate(df, 
          DTLTS     = TL - ((LWUP/5.67e-8)^0.25 - 273.15)
    )}

     if( all(c("LWUP", "TL", "FF") %in% names(df)) ){
         print("Adding derived parameter:  UDT")
         df <- mutate(df, 
          UDT     = TL - ((LWUP/5.67e-8)^0.25 - 273.15)  * FF
    )}
return(df)
}
```

Read observations

```{r, message=FALSE, "Read  mast data"}
#| echo: false

all_obs <- full_join( 
  lapply(metadata$Sites, function(mast){
    print(paste("reading mast data for", mast$name, "from", obs_path,sep=" "))
    read_mfile(mast = mast, 
               datadir=obs_path, 
               v_type="Mast")
  }) |> 
    bind_rows(),
  lapply(metadata$Sites, function(mast){
    print(paste("reading flux data from", mast$name, "from", obs_path,sep=" "))
    read_mfile(mast = mast, 
               datadir=obs_path, 
               v_type="Flux")
  }) |> bind_rows()
) |>
  add_derived_parameters()




```

Read forecasts

```{r, message=FALSE, "Read forecasts"}
#| echo: false

#The model data contains neither fcst_dttm nor lead time, but only the valid time.
#However, only forecasts from 00UTC are supposed to be used, and the first
#forecast should have a lead time of 1 hour, so, assuming 
#no errors, the missing data can be calculated. A check should be added, 
#to ensure that wrong data is excluded from further analysis.

# Compacting is for removing NULL_items in the case that 
# one or more models is not present at any site.
all_mods <- compact( 
  set_names(
  lapply(metadata$Models, function(model){
    lapply(metadata$Sites, function(mast){
      #print(paste(model$name, mast$models, sep=" "))
      if (grepl(model$name, mast$models)){ 
        print(paste("reading model output for", mast$name, model$name, 
                    "from", mod_path, sep=" "))
          read_mfile(mast=mast, 
                   model=model, 
                   datadir=mod_path, 
                   v_type="Model")
}
      }) |>
      bind_rows() |> 
      add_derived_parameters()
  }), sapply(metadata$Models, function(model){model$name})
  ))

```

Save configuration, metadata, and data in rds-file

```{r, "Save data  into an rds-file"}
#
saveRDS(list(data   = CONFIG$data, 
             metadata =CONFIG$metadata, 
             params   = CONFIG$params, 
             all_mods = all_mods, 
             all_obs  = all_obs),
             paste(rds_path,rdsfile,sep="/") )
print(paste0("saved data in ",paste(rds_path,rdsfile,sep="/")))
```

Read from an rds-file

```{r}

if (FALSE){
indata <- readRDS(paste(rds_path,rdsfile,sep="/"))
}
```

Compute and visualise as you whish--\>

```{r,  message=FALSE, "Compute and visualise", results="asis"}
#| echo: false
if (FALSE){
for (site in c("SODA")) {
#for (site in c("SODA","CABA","LIND")) {

  
  this_mast <- metadata$Sites[[{{site}}]]$SID
  mt <- unlist(strsplit(metadata$Sites[[{{site}}]]$Mast$parameters, ","))
  mt <- mt[mt != "valid_dttm"]
  fx <- unlist(strsplit(metadata$Sites[[{{site}}]]$Flux$parameters, ","))
  fx <- fx[fx != "valid_dttm"]
  #for (choice in c(mt, fx, "RNET","STH","RESID")) {
  for (choice in setdiff(c(mt, fx),"EVAP")) {
    
    # Note that removal of NAs is done in select_parameter
    
    
    object <- fn_select_parameter(all_obs, 
                               all_mods, 
                               choice, 
                               CONFIG$params_details[[choice]]$units,
                               SID=this_mast)
    
    if(!is.null(object)) {
      object <- check_obs_against_fcst(object, 
          {{choice}},
          num_sd_allowed = 6) |>
        expand_date(valid_dttm)
      
      tester <- do.call(rbind, 
                        lapply(object, function(model){
                          model |>
                            select( valid_dttm, 
                                    fcst, 
                                    all_of({{choice}}), 
                                    fcst_model, SID)
                        })) |>
        filter(SID=={{this_mast}})
      
      if (length( tester[[choice]]) > 0) {  
        print(c(site, choice))
        iwalk(
          list("valid_dttm", "valid_hour", "hexbin", "histogram", "cumhisto"),
          \(x,y) fn_plot_data_at_mast(
            fc_object           = object,
            plotvar             = choice, 
            SID                 = this_mast, 
            site                = site,
            plot_type_i         = y,
            plot_type           = x,
            rolling_mean_window = 3*24)
        )
      }
    }
    } # loop over parameters
  } # loop over sites
} # End of main if
```

```{r, message=FALSE, "det_verify stuff2"}
#| echo: false

#rerun verification setting obervation to 0, thus storing the parameter

#value in the columns for bias and mae

#dsc <- det_verify( # as_harp_list( # lapply(object, function(x){ # x |> mutate({{ choice }} := 0) # } # ) # ), # {{choice}}, # groupings = list( # c("lead_time", "mast"), # c("valid_dttm", "mast") ## ), # hexbin=TRUE, # thresholds = params[[{{choice}}]]$thresholds)

#hacking: replace column mae with the parameter value #vf$det_summary_scores$mae <- dsc$det_summary_scores$mae ## unfortunately the following does not work, as harp refuses to display ## columns with novel names ## vf$det_summary_scores <- vf$det_summary_scores |> rename(parameter = mae)

#save_point_verif(vf, here("verification")) #save_point_verif(dsc, here("description")) #shiny_plot_point_verif(here("verification"), full_dir_navigation = FALSE, theme#="light")
```
