# Section to define paths to mast verification data and 
# to define the mdoels presetn at each mast and the variables 
# of masts and modesl.to be used 

data:
  obs_path: "/ec/res4/scratch/fnm/MastVerifData/2023/JJA/obs"     #/home/fnm/rproj/mastverification/sampledata"
  mod_path: "/ec/res4/scratch/fnm/MastVerifData/2023/JJA/fc"     #/home/fnm/rproj/mastverification/sampledata"
  rds_input_path: "/perm/fnm/Site_data"
  rds_input_name: "2023_JJA.rds"
  
metadata:
  Sites:  
    SODA:
      name: SODA
      SID:  1
      lon: 26.67
      lat: 67.33
      elev: 180
      models: EC01, FRAR, MEP0
      Mast:
        parameters: valid_dttm,TT,TL,DT,RH,FF,GLOB,LWUP,LWDN,SWUP,SWDIF,DNI
      Flux:
        parameters: valid_dttm,SSH,SLH,EVAP,MOMF
    
    CABA:
      name: CABA
      SID:  2  
      lon: 4.927
      lat: 51.971
      elev: 10
      models: EC01, FRAR, MEP0, FARO
      Mast:
        parameters: valid_dttm,TT,TL,DT,RH,FF,GLOB,LWUP,LWDN,SWUP,SWDIF,DNI
      Flux:
        parameters: valid_dttm,SSH,SLH,EVAP,MOMF

    LIND:
      name: LIND
      SID:  3
      lon: 10
      lat: 47
      elev: 100
      models: EC01, FRAR, FARO
      Mast:
        parameters: valid_dttm,TT,TL,DT,RH,FF,GLOB,LWUP,LWDN,SWUP
      Flux:
        parameters: valid_dttm,SSH,SLH,EVAP,MOMF
      
  Models:
    MEP0:
      name: MEP0
      parameters: valid_dttm,TT,TL,DT,RH,FF,GLOB,LWUP,SSH,SLH,EVAP,MOMF,LWDN,SWUP,SWDIF,DNI
      minutefactor: 1
      first_lead_time: 3600
    EC01:
      name: EC01
      parameters: valid_dttm,TT,TL,DT,RH,FF,GLOB,LWUP,SSH,SLH,EVAP,MOMF
      minutefactor: 1
      first_lead_time: 0
    FRAR:
      name: FRAR
      parameters: valid_dttm,TT,TL,DT,RH,FF,GLOB,LWUP,SSH,SLH,EVAP,MOMF,LWDN,SWUP,SWDIF,DNI
      minutefactor: 1
      first_lead_time: 3600
    FARO:
      name: FARO
      parameters: valid_dttm,TT,TL,DT,RH,FF,GLOB,LWUP,SSH,SLH,PRES,MOMF,LWDN,SWUP,SWDIF,XX
      minutefactor: 100
      first_lead_time: 3600
